application: jeanlou-dupont
version: 1
api_version: 1
runtime: python


handlers:

#CLIENT
#======

 #old site compatibility
 #[old]
- url: /Main_Page
  script: server/oldsite/wiki.py
  
- url: /Extension:(.*)
  script: server/oldsite/wiki.py

- url: /Category:(.*)
  script: server/oldsite/wiki.py
  
- url: /Special:(.*)
  script: server/oldsite/wiki.py

- url: /Widget:(.*)
  script: server/oldsite/wiki.py
# [/old]

- url: /favicon.ico
  static_files: client/www/com.jldupont.project.main/favicon.ico
  upload: client/www/com.jldupont.project.main/favicon.ico

- url: /
  static_files: client/www/com.jldupont.project.main/main.html
  upload: client/www/com.jldupont.project.main/main.html

- url: /(.*\.(js|html|css|gif|png|jpg))
  static_files: client/www/com.jldupont.project.main/\1
  upload: client/www/com.jldupont.project.main/(.*\.(js|html|css|gif|png|jpg))

#SERVER
#======



# CATCH-ALL
- url: /.*
  static_files: server/default/not_found.html
  upload: server/default/not_found.html